/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface SpectrumWords {
    'lineSpacing': number;
    'paragraphCount': number;
    'paragraphLength': number[];
    'wordColors': string[] | string;
    'wordHeight': number;
    'wordSpacing': number;
    'wordWidths': number[] | string;
  }
}

declare global {


  interface HTMLSpectrumWordsElement extends Components.SpectrumWords, HTMLStencilElement {}
  var HTMLSpectrumWordsElement: {
    prototype: HTMLSpectrumWordsElement;
    new (): HTMLSpectrumWordsElement;
  };
  interface HTMLElementTagNameMap {
    'spectrum-words': HTMLSpectrumWordsElement;
  }
}

declare namespace LocalJSX {
  interface SpectrumWords {
    'lineSpacing'?: number;
    'paragraphCount'?: number;
    'paragraphLength'?: number[];
    'wordColors'?: string[] | string;
    'wordHeight'?: number;
    'wordSpacing'?: number;
    'wordWidths'?: number[] | string;
  }

  interface IntrinsicElements {
    'spectrum-words': SpectrumWords;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'spectrum-words': LocalJSX.SpectrumWords & JSXBase.HTMLAttributes<HTMLSpectrumWordsElement>;
    }
  }
}


